# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'RateExperienceForm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'lottie-ios', :git => "https://github.com/airbnb/lottie-ios"

  # Pods for RateExperienceForm

end
